server {
    listen 80;
    server_name traceforge.axiqo.xyz;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/faktura-acme;
    }

    location / {
        root /var/www/traceforge;
        try_files $uri $uri/ /index.html;
    }
}
