import { createHash, randomUUID } from "node:crypto";
import type { ReturnWorkflowInput, Scenario } from "./types.js";

const inventory = { sellable: 10, quarantine: 0 } as const;

/**
 * The experiment corpus is deliberately ordered by disclosure:
 *
 * 1. two operator-observed traces;
 * 2. the GPT-5.6-selected discriminating counterexample;
 * 3. exact deterministic boundary checks;
 *
 * The final held-out scenario is intentionally absent from this exported
 * corpus. The host creates it only after the Codex writing turn has ended.
 */
export const scenarios: Scenario[] = [
  {
    id: "observed-standard-damaged-4500",
    title: "Observed · standard damaged return",
    description: "The operator refunds a $45 damaged return and quarantines the unit.",
    stage: "observed",
    visibility: "visible",
    provenance: {
      source: "host-authored",
      detail: "Operator-observed trace selected by the host as source evidence.",
    },
    input: {
      returnId: "RET-OBS-001",
      sku: "SKU-COPPER-01",
      amountCents: 4_500,
      customerTier: "STANDARD",
      itemCondition: "DAMAGED",
      initialInventory: { ...inventory },
    },
  },
  {
    id: "observed-vip-damaged-12000",
    title: "Observed · VIP damaged return",
    description: "The operator replaces a $120 VIP return and quarantines the damaged unit.",
    stage: "observed",
    visibility: "visible",
    provenance: {
      source: "host-authored",
      detail: "Operator-observed trace selected by the host as source evidence.",
    },
    input: {
      returnId: "RET-OBS-002",
      sku: "SKU-COPPER-01",
      amountCents: 12_000,
      customerTier: "VIP",
      itemCondition: "DAMAGED",
      initialInventory: { ...inventory },
    },
  },
  {
    id: "counterexample-vip-damaged-50000",
    title: "Host-derived counterexample · priority at the boundary",
    description: "The host crosses customer tier at the exact review boundary to distinguish threshold priority from VIP replacement.",
    stage: "counterexample",
    visibility: "visible",
    provenance: {
      source: "host-derived",
      detail: "Derived by the host from the model-discovered high-value exception and executed before the Codex writing turn.",
    },
    input: {
      returnId: "RET-CHALLENGE-001",
      sku: "SKU-COPPER-01",
      amountCents: 50_000,
      customerTier: "VIP",
      itemCondition: "DAMAGED",
      initialInventory: { ...inventory },
    },
  },
  {
    id: "boundary-standard-damaged-49999",
    title: "Boundary · one cent below review",
    description: "$499.99 remains eligible for automatic refund and quarantine.",
    stage: "boundary",
    visibility: "visible",
    provenance: {
      source: "host-authored",
      detail: "Deterministic boundary case authored and executed by the host verifier.",
    },
    input: {
      returnId: "RET-BOUNDARY-LOW",
      sku: "SKU-COPPER-01",
      amountCents: 49_999,
      customerTier: "STANDARD",
      itemCondition: "DAMAGED",
      initialInventory: { ...inventory },
    },
  },
  {
    id: "boundary-standard-damaged-50000",
    title: "Boundary · exact review threshold",
    description: "$500.00 is the first value that requires review with no inventory or payment side effects.",
    stage: "boundary",
    visibility: "visible",
    provenance: {
      source: "host-authored",
      detail: "Deterministic boundary case authored and executed by the host verifier.",
    },
    input: {
      returnId: "RET-BOUNDARY-EXACT",
      sku: "SKU-COPPER-01",
      amountCents: 50_000,
      customerTier: "STANDARD",
      itemCondition: "DAMAGED",
      initialInventory: { ...inventory },
    },
  },
];

/**
 * Creates the concrete final verification input from host-only entropy.
 *
 * The generator code is public, but the nonce and therefore the amount,
 * identity, SKU, and initial state do not exist until the host invokes this
 * function after the Codex turn. Supplying a nonce is only for deterministic
 * host tests; production callers deliberately omit it.
 */
export function createHostHiddenScenario(nonce: string = randomUUID()): Scenario {
  const hash = createHash("sha256").update(nonce).digest("hex");
  const offset = (Number.parseInt(hash.slice(0, 8), 16) % 10_000) + 1;
  const sellable = 3 + (Number.parseInt(hash.slice(8, 10), 16) % 8);
  const quarantine = Number.parseInt(hash.slice(10, 12), 16) % 4;
  const suffix = hash.slice(12, 24);
  return {
    id: `host-hidden-${suffix}`,
    title: "Host-generated covered-domain probe",
    description: "Generated after the writer exits; its concrete amount, identity, SKU, and state were never disclosed to Codex.",
    stage: "held-out",
    visibility: "hidden",
    provenance: {
      source: "host-authored",
      detail: "Concrete VIP damaged-return input generated by the host after the Codex writing turn.",
    },
    input: {
      returnId: `RET-HOST-HIDDEN-${suffix.toUpperCase()}`,
      sku: `SKU-HOST-${hash.slice(24, 32).toUpperCase()}`,
      amountCents: 50_000 + offset,
      customerTier: "VIP",
      itemCondition: "DAMAGED",
      initialInventory: { sellable, quarantine },
    },
  };
}

const legacyScenarioAliases: Readonly<Record<string, string>> = {
  "damaged-small-refund": "observed-standard-damaged-4500",
  "vip-damaged-replacement": "observed-vip-damaged-12000",
  "high-value-review": "counterexample-vip-damaged-50000",
};

export function findScenario(id: string): Scenario | undefined {
  const canonicalId = legacyScenarioAliases[id] ?? id;
  return scenarios.find((scenario) => scenario.id === canonicalId);
}

export function validateWorkflowInput(value: unknown): ReturnWorkflowInput {
  if (!value || typeof value !== "object") {
    throw new Error("input must be an object");
  }
  const input = value as Partial<ReturnWorkflowInput>;
  if (!input.returnId?.trim() || !input.sku?.trim()) {
    throw new Error("returnId and sku are required");
  }
  if (!Number.isInteger(input.amountCents) || (input.amountCents ?? 0) <= 0) {
    throw new Error("amountCents must be a positive integer");
  }
  if (input.customerTier !== "STANDARD" && input.customerTier !== "VIP") {
    throw new Error("customerTier must be STANDARD or VIP");
  }
  if (input.itemCondition !== "SELLABLE" && input.itemCondition !== "DAMAGED") {
    throw new Error("itemCondition must be SELLABLE or DAMAGED");
  }
  const initialInventory = input.initialInventory ?? { sellable: 10, quarantine: 0 };
  if (
    !Number.isInteger(initialInventory.sellable) ||
    !Number.isInteger(initialInventory.quarantine) ||
    initialInventory.sellable < 0 ||
    initialInventory.quarantine < 0
  ) {
    throw new Error("initialInventory quantities must be non-negative integers");
  }
  return {
    returnId: input.returnId,
    sku: input.sku,
    amountCents: input.amountCents as number,
    customerTier: input.customerTier,
    itemCondition: input.itemCondition,
    initialInventory: { ...initialInventory },
  };
}
